### ISSUE TITLE
is s3 a requirement?

### ISSUE THREAD

**Issue by ralyodio** [staab/dufflepud#2]
Seems like this should be a docker-compose.yml instance. would be way easyier to install. I don't know how to run or setup postgres.

**Comment by staab** [comment]
PRs welcome, I don't personally use docker, but you can feel free to contribute any dockerfile you come up with..

**Comment by ralyodio** [comment]
Is s3 still a requirement? or can you store locally on server?

**Comment by staab** [comment]
Oh, I see, right now it is (I don't use s3, I use linode object storage), but it should be easy to change to store locally.

**Comment by ralyodio** [comment]
ok maybe a `FILE_STORAGE_PATH=./data/foo`
